### PR TITLE
Various AppStream metadata fixes

### PR DESCRIPTION
**Pull request by AsciiWolf**
1. Lang "cz" is incorrect, the correct one for Czech is "cs",
2. fix typos in Czech summary by using the actual one from upstream desktop file,
3. it's "Wine", not "W.I.N.E.".

### CODE REVIEW

**Comment by tim77** [comment]
Thanks. Upstream review got stuck. As for point 4:

Upstream use this summary:
изображение

As for point 3:
Fedora downstream appdata is terrible and not the best example. This is Qt app, why gettext?

**Comment by AsciiWolf** [comment]
Point 4: The upstream summary is clearly incorrect. There is no such thing as "W.I.N.E.".

Point 3: Because `gettext` seems to work and correctly displays the translated strings in Fedora. But it may be a Flathub issue, I am not sure, so feel free to edit the PR and not merge this change.

**Comment by tim77** [comment]
> Point 4: The upstream summary is clearly incorrect. There is no such thing as "W.I.N.E.".

Yep, we should also suggest upstream fix.

> Point 3: Because gettext seems to work and correctly displays the translated strings in Fedora. But it may be a Flathub issue, I am not sure, so feel free to edit the PR and not merge this change.

It works correctly as well for me, this Flathub version. This appdata tag has nothing to do with translations in app itself. It show in front-ends like Gnome Software on which languages app translated. This feature works in earlier version on Gnome Software but i don't know why it doesn't exist.

Let's continue to work on fixes here https://github.com/brezerk/q4wine/pull/194.

**Comment by AsciiWolf** [comment]
I have removed the translation type change.

**Comment by tim77** [comment]
Thanks! :+1:

**Pull request merged**
